// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPwhZSSW8Be8E6JoJB1_Hy-WYcjbWjGKk',
    appId: '1:783778456608:web:e237522ff8f1aedeca0845',
    messagingSenderId: '783778456608',
    projectId: 'myexercises-d4f5a',
    authDomain: 'myexercises-d4f5a.firebaseapp.com',
    storageBucket: 'myexercises-d4f5a.firebasestorage.app',
    measurementId: 'G-3BBMBCMNZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDY2PCud-qGGcDql-pMHbcp41eqwIdTkY',
    appId: '1:783778456608:android:096fe08c5907ac76ca0845',
    messagingSenderId: '783778456608',
    projectId: 'myexercises-d4f5a',
    storageBucket: 'myexercises-d4f5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb1IDbzMg4H0QXip7BVqIptXs9gUzMoTA',
    appId: '1:783778456608:ios:a7a8fe5e52b262a6ca0845',
    messagingSenderId: '783778456608',
    projectId: 'myexercises-d4f5a',
    storageBucket: 'myexercises-d4f5a.firebasestorage.app',
    iosClientId: '783778456608-ic2rt8pvmnf0r9nou52d09fgtfqf43ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.myExercises',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb1IDbzMg4H0QXip7BVqIptXs9gUzMoTA',
    appId: '1:783778456608:ios:a7a8fe5e52b262a6ca0845',
    messagingSenderId: '783778456608',
    projectId: 'myexercises-d4f5a',
    storageBucket: 'myexercises-d4f5a.firebasestorage.app',
    iosClientId: '783778456608-ic2rt8pvmnf0r9nou52d09fgtfqf43ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.myExercises',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPwhZSSW8Be8E6JoJB1_Hy-WYcjbWjGKk',
    appId: '1:783778456608:web:58186d4c00968405ca0845',
    messagingSenderId: '783778456608',
    projectId: 'myexercises-d4f5a',
    authDomain: 'myexercises-d4f5a.firebaseapp.com',
    storageBucket: 'myexercises-d4f5a.firebasestorage.app',
    measurementId: 'G-TPL3SWPQGC',
  );
}
